version: '3.1'

services:
   web:
      build: .
      volumes:
         - .:/src
      command: npm run start:docker
      depends_on:
         db:
            condition: service_started
      ports:
         - 3000:3000
      networks:
         - backend
      environment:
         HOST_DB: challenge_database
         USER_DB: postgres
         PASS_DB: root
         NAME_DB: challenge

   db:
      image: postgres
      container_name: challenge_database
      restart: always
      environment:
         POSTGRES_PASSWORD: root
         POSTGRES_DB: challenge
      ports:
         - 5432:5432
      networks:
         - backend

networks:
   backend: